name: FilterCraft-macOS
options:
  bundleIdPrefix: com.filtercraft
  deploymentTarget:
    macOS: '12.0'

packages:
  FilterCraftCore:
    path: ../../Packages/FilterCraftCore

targets:
  FilterCraft-macOS:
    type: application
    platform: macOS
    deploymentTarget: '12.0'
    sources:
      - Sources
    resources:
      - Resources/**/*
    dependencies:
      - package: FilterCraftCore
    info:
      path: Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.filtercraft.macos
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      SWIFT_VERSION: 5.0
      MACOSX_DEPLOYMENT_TARGET: 12.0
    entitlements:
      path: FilterCraft-macOS.entitlements
    scheme:
      gatherCoverageData: true
      
  FilterCraft-macOSTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests
    dependencies:
      - target: FilterCraft-macOS
    settings:
      BUNDLE_LOADER: $(TEST_HOST)
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/FilterCraft-macOS.app/Contents/MacOS/FilterCraft-macOS